config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :parties
  resources :menus
  resources :users, only: [:index, :show] do
    post 'update_invites'
  end
  
  post 'add_contribution',:to => "home#add_contribution"
  post 'revert_contribution',:to => "home#revert_contribution"
  post 'add_order',:to => "home#add_order"
  
  root to: 'home#index'
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :party
  has_many :users_parties
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :contact)
    end
end

app/views/menus/_form.html.slim
= party_form_for(@menu) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :price

  .form-actions
    = f.button :submit

app/views/menus/edit.html.slim
h1 Editing menu

== render 'form'

= link_to 'Show', @menu
'|
= link_to 'Back', menus_path

app/views/menus/index.html.slim
h1 Listing products

table
  thead
    tr
      th Name
      th Contact
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.contact
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_product_path

app/views/menus/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/menus/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name
p
  strong Contact:
  = @product.contact

= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path