config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :parties
  resources :menus
  resources :users, only: [:index, :show] do
    post 'update_invites'
  end
  
  post 'add_contribution',:to => "home#add_contribution"
  post 'revert_contribution',:to => "home#revert_contribution"
  post 'add_order',:to => "home#add_order"
  
  root to: 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :parties
  has_many :users_parties, through: :parties

  scope :invite_members, -> (user_id) { where('id !=?', user_id) }
  scope :has_birthday, -> (date,user_id) { where('dob =? and id=?', date, user_id) }

  def birthday?
    dob == Date.today
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.invite_members current_user.id
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def update_invites
    invite_ids = params[:invitee_ids]
    invite_ids.each do |invite|
      Party.find_or_create_by(bid: current_user.id,invitee_id: invite)
      # binding.pry
    end
    redirect_to users_path,notice: 'You have invited users successfully.'
  end
  
end

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= check_box_tag 'invitee_ids[]',user.id %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <%= form_tag(update_invites_users_path) do |f| %>
        <table class="table">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <%= render user %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= submit_tag 'Invite' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>