config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :parties
  resources :menus
  resources :users, only: [:index, :show] do
    post 'update_invites'
  end
  
  post 'add_contribution',:to => "home#add_contribution"
  post 'revert_contribution',:to => "home#revert_contribution"
  post 'add_order',:to => "home#add_order"
  
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
    @party = Party.new
    # @birthday_person = User.has_birthday Date.today, current_user.id
    # @my_invites = Party.has_invited current_user.id
    # @menus = Menu.all
  end

  def add_contribution
    get_party params[:bid], true
  end

  def revert_contribution
    get_party params[:bid], false
  end

  def add_order
    @party = Party.find(params[:invite_id])
    @pizza_menu = Menu.find_by(name:'Pizza')
    if params[:menu_id].to_i == @pizza_menu.id
      @party.update_attributes(menu_id: params[:menu_id], bid: params[:birthday_id],invitee_id: current_user[:id],extra: '')
      redirect_to visitors_path,:notice =>'You have added your order successfully'
    else
      if @party.update_attributes(menu_id: params[:menu_id], bid: params[:birthday_id],invitee_id: current_user[:id],extra: params[:extra])
        redirect_to visitors_path,:notice =>'You have added your order successfully'
      else
        redirect_to visitors_path,:alert =>"Error updating your order - #{@party.errors.full_messages.first}"
      end
    end
  end
  
  private

  def get_party bid, contributed
    @contribution = Party.find_by_bid_and_invitee_id(bid,current_user.id)
    @contribution.is_contributed =  contributed
    @contribution.save
    redirect_to visitors_path
  end
end

app/views/home/index.html.slim
#party.cards.col-md-4
  .panel.panel-default
    .panel-heading
      h3.panel-title Throw party
    .panel-body
      = render 'parties/form'

#invitations.cards.col-md-4
  .panel.panel-default
    .panel-heading
      h3.panel-title Invitations
    .panel-body
      - if @my_invites
        - @my_invites.each do |invite|
          .well.well-lg
            p
              | You got an invitation from
              i= invite.birthday.name
            - if invite.is_contributed?
              p
                | Do you want to revert your #{link_to "Contribute",revert_contribution_path(:bid=> invite.bid),method: :post}
            - else
              p
                | Would you like to  #{link_to "Contribute",add_contribution_path(:bid=> invite.bid),method: :post}
              p
                | Tell what you want to have for party
              = form_tag(add_order_path,class: 'form-horizontal') do |f|
                = hidden_field_tag 'birthday_id', invite.birthday.id
                = hidden_field_tag 'invite_id', invite.id
                .form-group.col-sm-4
                  = select_tag "product_id", options_from_collection_for_select(@products, "id", "name",invite.product_id), class: 'form-control product_id',id: invite.id
                .row
                .form-group.col-sm-4
                  = text_field_tag 'extra', invite.extra, class: "form-control #{invite.is_pizza_product? ? 'hidden' : ''}", id: "extra-#{invite.id}",placeholder: 'Specify your dish'
                .row
                .form-group
                  = submit_tag 'sumbit',class: 'btn btn-primary'

#notifications.cards.col-md-4
  .panel.panel-default
    .panel-heading
      h3.panel-title Invitations
    .panel-body
      /- if current_user.birthday?
      p Today is your birthday!!!

javascript:
  $(document).ready(function() {
    
    $('.product_id').click(function() {
      var product = $(this).find(":selected").text();
      if (product != 'Pizza'){
        $('#extra-'+$(this).attr('id')).show();
        $('#extra-'+$(this).attr('id')).removeClass('hidden')
      }
      else{
        $('#extra-'+$(this).attr('id')).hide()
      }
    });
  });

app/views/home/show.html.erb
<p>show page</p>